[package]
name = "kampfkarren/hoarcekat"
version = "1.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
RoactRodux = "roblox/roact-rodux@0.3.0"
Rodux = "roblox/rodux@3.0.0"
